# Generated by Django 4.2.4 on 2023-10-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
    ]
