# Generated by Django 4.2.4 on 2023-10-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='prod_code',
            new_name='prod_ref',
        ),
    ]
